export const ADD_TO_PENDING_ITEMS = 'ADD_TO_PENDING_ITEMS'; // inventory
export const ADD_TO_PENDING_SALES_ITEMS = 'ADD_TO_PENDING_SALES_ITEMS'; // sales
export const REMOVE_ALL_PENDING_ITEMS = 'REMOVE_ALL_PENDING_ITEMS';
export const REMOVE_SINGLE_PENDING_ITEMS = 'REMOVE_SINGLE_PENDING_ITEMS';

export const UPDATE_SEARCH_RESULTS = 'UPDATE_SEARCH_RESULTS';

export const UPDATE_ITEM_TEXT = 'UPDATE_ITEM_TEXT';
export const UPDATE_ITEM_BARCODE = 'UPDATE_ITEM_BARCODE';
export const UPDATE_ITEM_PRICE = 'UPDATE_ITEM_PRICE';
export const UPDATE_ITEM_REMAINING = 'UPDATE_ITEM_REMAINING';

export const UPDATE_QUANTITY = 'UPDATE_QUANTITY';

export const UPDATE_SUPPLIERS = 'UPDATE_SUPPLIERS';
export const UPDATE_SUPPLIER_SELECTED_ID = 'UPDATE_SUPPLIER_SELECTED_ID';

export const UPDATE_PRICE = 'UPDATE_PRICE';

export const UPDATE_KILO = 'UPDATE_KILO';

export const UPDATE_DISCOUNT = 'UPDATE_DISCOUNT';

export const UPDATE_SACKS = 'UPDATE_SACKS';
export const UPDATE_SACK_SELECTED_VALUE = 'UPDATE_SACK_SELECTED_VALUE';
