export const ADD_TO_PENDING_ITEMS = 'ADD_TO_PENDING_ITEMS'; // inventory
export const ADD_TO_PENDING_SALES_ITEMS = 'ADD_TO_PENDING_SALES_ITEMS'; // sales
export const REMOVE_ALL_PENDING_ITEMS = 'REMOVE_ALL_PENDING_ITEMS';
export const REMOVE_SINGLE_PENDING_ITEMS = 'REMOVE_SINGLE_PENDING_ITEMS';

export const UPDATE_SEARCH_RESULTS = 'UPDATE_SEARCH_RESULTS';

export const UPDATE_QUANTITY = 'UPDATE_QUANTITY';

export const UPDATE_SUPPLIERS = 'UPDATE_SUPPLIERS';

export const UPDATE_KILO = 'UPDATE_KILO';

export const UPDATE_DISCOUNT = 'UPDATE_DISCOUNT';

export const UPDATE_SACKS = 'UPDATE_SACKS';
export const UPDATE_SACK_SELECTED_VALUE = 'UPDATE_SACK_SELECTED_VALUE';
