export const ADD_TO_PENDING_ITEMS = 'ADD_TO_PENDING_ITEMS';
export const REMOVE_ALL_PENDING_ITEMS = 'REMOVE_ALL_PENDING_ITEMS';
export const REMOVE_SINGLE_PENDING_ITEMS = 'REMOVE_SINGLE_PENDING_ITEMS';

export const UPDATE_SEARCH_RESULTS = 'UPDATE_SEARCH_RESULTS';

export const UPDATE_QUANTITY = 'UPDATE_QUANTITY';

export const UPDATE_SUPPLIERS = 'UPDATE_SUPPLIERS';
